// import {User} from "./User.ts";
// console.log("user details");
// let user = new User();
// console.log(user.name);
// console.log(user.location.lat);
// console.log(user.location.lng);

// console.log("############");
// console.log("Company Details:");
// import {Company} from "./Company.ts";
// let company = new Company();
// console.log(company.companyName);
// console.log(company.catchPhrase);
// console.log(company.location);
import {User} from "./User";
import {CustomMap} from "./CustomMap";
import {Company} from "./Company";
let OurMap = new CustomMap('mapzz');
let user = new User();
let company = new Company();
OurMap.addMarker(user);
OurMap.addMarker(company);